/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SecretariatRouteImport } from './routes/secretariat'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DelegatesRouteImport } from './routes/delegates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretariatRoute = SecretariatRouteImport.update({
  id: '/secretariat',
  path: '/secretariat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegatesRoute = DelegatesRouteImport.update({
  id: '/delegates',
  path: '/delegates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/gallery': typeof GalleryRoute
  '/schedule': typeof ScheduleRoute
  '/secretariat': typeof SecretariatRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/gallery': typeof GalleryRoute
  '/schedule': typeof ScheduleRoute
  '/secretariat': typeof SecretariatRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/gallery': typeof GalleryRoute
  '/schedule': typeof ScheduleRoute
  '/secretariat': typeof SecretariatRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/committees'
    | '/contact'
    | '/delegates'
    | '/gallery'
    | '/schedule'
    | '/secretariat'
    | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/committees'
    | '/contact'
    | '/delegates'
    | '/gallery'
    | '/schedule'
    | '/secretariat'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/committees'
    | '/contact'
    | '/delegates'
    | '/gallery'
    | '/schedule'
    | '/secretariat'
    | '/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  CommitteesRoute: typeof CommitteesRoute
  ContactRoute: typeof ContactRoute
  DelegatesRoute: typeof DelegatesRoute
  GalleryRoute: typeof GalleryRoute
  ScheduleRoute: typeof ScheduleRoute
  SecretariatRoute: typeof SecretariatRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretariat': {
      id: '/secretariat'
      path: '/secretariat'
      fullPath: '/secretariat'
      preLoaderRoute: typeof SecretariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegates': {
      id: '/delegates'
      path: '/delegates'
      fullPath: '/delegates'
      preLoaderRoute: typeof DelegatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  CommitteesRoute: CommitteesRoute,
  ContactRoute: ContactRoute,
  DelegatesRoute: DelegatesRoute,
  GalleryRoute: GalleryRoute,
  ScheduleRoute: ScheduleRoute,
  SecretariatRoute: SecretariatRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
