/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretariatRouteImport } from './routes/secretariat'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as DelegatesRouteImport } from './routes/delegates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as IndexRouteImport } from './routes/index'

const SecretariatRoute = SecretariatRouteImport.update({
  id: '/secretariat',
  path: '/secretariat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegatesRoute = DelegatesRouteImport.update({
  id: '/delegates',
  path: '/delegates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/schedule': typeof ScheduleRoute
  '/secretariat': typeof SecretariatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/schedule': typeof ScheduleRoute
  '/secretariat': typeof SecretariatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/schedule': typeof ScheduleRoute
  '/secretariat': typeof SecretariatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/committees'
    | '/contact'
    | '/delegates'
    | '/schedule'
    | '/secretariat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/committees'
    | '/contact'
    | '/delegates'
    | '/schedule'
    | '/secretariat'
  id:
    | '__root__'
    | '/'
    | '/committees'
    | '/contact'
    | '/delegates'
    | '/schedule'
    | '/secretariat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitteesRoute: typeof CommitteesRoute
  ContactRoute: typeof ContactRoute
  DelegatesRoute: typeof DelegatesRoute
  ScheduleRoute: typeof ScheduleRoute
  SecretariatRoute: typeof SecretariatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretariat': {
      id: '/secretariat'
      path: '/secretariat'
      fullPath: '/secretariat'
      preLoaderRoute: typeof SecretariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegates': {
      id: '/delegates'
      path: '/delegates'
      fullPath: '/delegates'
      preLoaderRoute: typeof DelegatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitteesRoute: CommitteesRoute,
  ContactRoute: ContactRoute,
  DelegatesRoute: DelegatesRoute,
  ScheduleRoute: ScheduleRoute,
  SecretariatRoute: SecretariatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
